export enum ActionType  {
    ERROR ='ERROR',
    LOADING = 'LOADING',
    START_GAME= 'START_GAME',
    RESTART_GAME = 'RESTART_GAME',
    NEXT_QUESTION = 'NEXT_QUESTION',
    CHECK_ANSWER = 'CHECK_ANSWER',
    GET_DATA = 'GET_DATA',
    SET_USER_ANSWER = 'SET_USER_ANSWER',
}